### ISSUE TITLE
ModuleNotFoundError with lazy Angular modules on AoT build

### ISSUE THREAD

**Issue by lambourn** [NativeScript/nativescript-dev-webpack#832]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.2.0
 - Cross-platform modules: 5.2.2
 - Android Runtime: 5.2.1
 - iOS Runtime: 5.2.0
 - Plugin(s): nativescript-dev-webpack 0.20.2
 - Node.js: 10.15.2
 
**Describe the bug**

After migrating our 4.x / Angular 6.x codebase to {N} 5.x and Angular 7.2.2 our Webpack AoT build is failing, webpack.config.js has been replaced by the latest as provided by the nativescript-dev-webpack plugin.

The application uses lazy Angular modules. During AoT compilation the build fails with a `ModuleNotFoundError` while processing the route information for the lazy loaded modules (this does not happen on non-AoT Webpack build)

Error:
```
ModuleNotFoundError: Module not found: Error: Can't resolve '/Users/cdds/dev/control-modularized/apps/control-app/app/components/devicescanner/devicescanner.module.ngfactory.js' in '/Users/cdds/dev/control-modularized/apps/control-app/$$_lazy_route_resource'
...
```
Corresponding `app.routing.ts` snippet:
```
const APP_ROUTES: Routes = [
  { path: "devicescanner", loadChildren: "~/components/devicescanner/devicescanner.module#DeviceScannerModule" },
  ...
];
export const routing = NativeScriptRouterModule.forRoot(APP_ROUTES);
```
The exported `routing` is imported in the main `app.module.ts`. 

This all works fine with {N} 4.2 but does not work with 5.2

Any ideas how to workaround/configure it properly?

**Comment by NickIliev** [comment]
@lambourn try removing the tilde from the lazily loaded path.

e.g.  change it to:
```TS
const APP_ROUTES: Routes = [
  { path: "devicescanner", loadChildren: "./components/devicescanner/devicescanner.module#DeviceScannerModule" },
  ...
];
```

**Comment by lambourn** [comment]
@NickIliev already did - to no avail. I'm currently try to create a isolated setup to repro it.

**Comment by NickIliev** [comment]
@lambourn will wait for your repro app - meanwhile, use[ this one as a reference](https://github.com/NickIliev/nativescript-ng-cosmos/blob/master/app/app.routing.ts#L13) (the app is using lazily loaded modules with all dependencies to latest and is building with AOT).

**Comment by lambourn** [comment]
@NickIliev thanks. When I create a new ng project with `tns create`, use a lazy-loaded module and AoT it, it also works for me. Just with the legacy app migrated to 5.2 it does not work. 

Meanwhile, I found that this error also happens when I invoke `webpack.js` directly, passing in the `webpack.config.js` etc. - so it's somewhere down there.

**Comment by lambourn** [comment]
I found out is that the error `ModuleNotFoundError: Module not found: Error: Can't resolve ... $$_lazy_route_resource` is a follow-up error due to a `.ts` compilation error. However this real root-cause is not reported by the bundler.

I found this accidentally when I ran `tsc` alone and got the error reported immediately.

**Comment by lambourn** [comment]
ok, found it. For our CI builds we added `bail = true` to the `webpack.config.js` which causes Webpack to stop processing on first error and exit immediately. 

However, when building for lazy-loaded modules, Webpack will by default continue build, then pick-up the original error that caused compilation to fail and print it in the compilation error message. Due to bailing, that original error never got reported.

I removed the `bail = true` from Webpack config which fixes the issue for us.
