### ISSUE TITLE
Unable to run app with CLI 5.4 and nativescript-dev-webpack@6.0

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-dev-webpack#945]
**Describe the bug**

Unable to run the application with  {N} CLI 5.4 and `nativescript-dev-webpack@6.0.0` with legacy workflow.

**Additional context**

There are breaking changes in `nativescript-dev-webpack` hooks which we could not take into account in this scenario.

**Comment by Cross77** [comment]
Error is:
`Cannot find module 'nativescript-dev-webpack/lib/before-watchPatterns.js'`

**Comment by ManfrediPist** [comment]
Same story here, I think we must downgrade web pack version to one containing that js, to come back working

**Comment by Cross77** [comment]
@ManfrediPist 
Yeap, it's working on the last stable release 0.24.1: 
`"nativescript-dev-webpack": "0.24.1",`
