### ISSUE TITLE
Need Help: Webpack not working for NativeScript 3 and Angular 4

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-dev-webpack#198]
_From @NathakornJ on June 22, 2017 7:0_

I am working on webpack for a {N} 3.0 + Angular 4 project according to instructions from https://docs.nativescript.org/tooling/bundling-with-webpack. 
When I run >> **npm run build-android-bundle** OR **npm run start-android-bundle**, it excepts with following error:

> @ build-android-bundle D:\Source\NS\Hallo
> npm run ns-bundle --android --build-app

> @ ns-bundle D:\Source\NS\Hallo
> ns-bundle

Running webpack for android...
module.js:471
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Source\NS\Hallo\webpack.config.js:3:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
child process exited with code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ ns-bundle: `ns-bundle`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ ns-bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nathakorn\AppData\Roaming\npm-cache\_logs\2017-06-22T06_44_34_971Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build-android-bundle: `npm run ns-bundle --android --build-app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build-android-bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nathakorn\AppData\Roaming\npm-cache\_logs\2017-06-22T06_44_35_008Z-debug.log

**Here is my package.json file:**
"dependencies": {
    "@angular/animations": "^4.1.2",
    "@angular/common": "^4.1.3",
    "@angular/compiler": "^4.1.3",
    "@angular/core": "^4.1.3",
    "@angular/forms": "^4.1.3",
    "@angular/http": "^4.1.3",
    "@angular/platform-browser": "^4.1.3",
    "@angular/platform-browser-dynamic": "^4.1.2",
    "@angular/router": "^4.1.3",
    "faker": "^4.1.0",
    "nativescript-angular": "^3.0.0",
    "nativescript-angular-snapshot": "3.0.0-5.5.372.32",
    "nativescript-barcodescanner": "^2.5.0",
    "nativescript-camera": "^3.0.0",
    "nativescript-drop-down": "^3.0.2",
    "nativescript-emoji": "^1.1.1",
    "nativescript-grid-view": "^3.0.0",
    "nativescript-image-file": "file:local-plugins\\nativescript-image-file",
    "nativescript-imagecropper": "0.0.7",
    "nativescript-ripple": "^2.0.0",
    "nativescript-screen": "file:local-plugins\\nativescript-screen",
    "nativescript-social-share": "^1.3.2",
    "nativescript-telerik-ui": "^2.0.1",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-videoplayer": "^3.0.7",
    "nativescript-web-image-cache": "^4.1.0",
    "nativescript-zoomable-image": "file:local-plugins\\nativescript-zoomable-image",
    "nativescript-zxing": "^1.5.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "^5.4.0",
    "thenby": "^1.2.3",
    "tns-core-modules": "^3.0.1",
    "tns-platform-declarations": "^3.0.1",
    "zone.js": "^0.8.12"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^4.1.3",
    "@ngtools/webpack": "~1.4.0",
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "copy-webpack-plugin": "~4.0.1",
    "extract-text-webpack-plugin": "~2.1.0",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "^0.4.5",
    "nativescript-dev-webpack": "^0.6.3",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.0.2",
    "typescript": "~2.2.1",
    "webpack": "~2.6.1",
    "webpack-sources": "~1.0.1"
  },
  "scripts": {
    "ns-bundle": "ns-bundle",
    "start-android-bundle": "npm run ns-bundle --android --run-app",
    "start-ios-bundle": "npm run ns-bundle --ios --run-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app",
    "publish-ios-bundle": "npm run ns-bundle --ios --publish-app"
  }

_Copied from original issue: NativeScript/NativeScript#4439_

**Comment by tsonevn** [comment]
Hi @NathakornJ,

I tested your case while using the attached `package.json` file, however, was unable to reproduce an issue with the `webpack`. 
Something that could be related to this issue is the plugins which are installed from the local `tgz` files and the fact that they might be incompatible with the `nativescript-dev-webpack`. Just for the test you could remove them from the project and try to webpack the project again. 

In the meantime, you could also try to remove `platforms`, `node_modules`, `hooks` folders and to follow the below-attached steps below:

1. `npm install`
2. `npm run start-android-bundle`

**Comment by NathakornJ** [comment]
**Can you test it again as followings:**
1. tns create testWebPack --ng
2. cd testWebPack
3. npm install --save-dev nativescript-dev-webpack
4. npm install
5. npm run start-android-bundle OR npm run build-android-bundle

I just did it and it did not work. Please.

**Comment by NathakornJ** [comment]
*Can you test it again as followings:*

 1. tns create testWebPack --ng
 2. cd testWebPack
 3. npm install --save-dev nativescript-dev-webpack
 4. npm install
 5. npm run start-android-bundle OR npm run build-android-bundle

I just did it and it did not work.

*I need to resolve this issue since {N} + Angular starts up very very 
slow. I am hoping that the webpack can help.*


Regards,
*Nathakorn J.*
Softoo Systems Co., Ltd.
www.softoo.co.th

**Comment by tsonevn** [comment]
Hi @NathakornJ,
I tested the described steps and still, the app is built properly while using webpack. Could you check whether you are using latest CLI 3.0.3-> `tns --version`.
Also regarding the latest comment, to make your app faster you could also apply to your project the `lazy loading` technic for your NativeScirpt Angular 2 project. More about it could be found [here](https://www.nativescript.org/blog/optimizing-app-loading-time-with-angular-2-lazy-loading).

**Comment by NathakornJ** [comment]
Refer to the lazy loading you mentioned, yes, I will try it again. But I 
used to test my project by removing all pages/modules but leave only one 
page /module. It was slow.

*I am interesting in webpack.* And yes, *tns --version returns 3.0.3*

Can you share your package.json and webpack.config.js files. Here are mine.

*package.json*

{
   "description": "NativeScript Application",
   "license": "SEE LICENSE IN <your-license-filename>",
   "readme": "NativeScript Application",
   "repository": "<fill-your-repository-here>",
   "nativescript": {
     "id": "org.nativescript.testWebPack",
     "tns-android": {
       "version": "3.0.1"
     }
   },
   "dependencies": {
     "@angular/animations": "~4.1.0",
     "@angular/common": "~4.1.0",
     "@angular/compiler": "~4.1.0",
     "@angular/core": "~4.1.0",
     "@angular/forms": "~4.1.0",
     "@angular/http": "~4.1.0",
     "@angular/platform-browser": "~4.1.0",
     "@angular/router": "~4.1.0",
     "nativescript-angular": "~3.0.0",
     "nativescript-theme-core": "~1.0.2",
     "reflect-metadata": "~0.1.8",
     "rxjs": "~5.3.0",
     "tns-core-modules": "~3.0.0",
     "zone.js": "~0.8.2"
   },
   "devDependencies": {
     "@angular/compiler-cli": "~4.1.0",
     "@ngtools/webpack": "~1.4.0",
     "babel-traverse": "6.4.5",
     "babel-types": "6.4.5",
     "babylon": "6.4.5",
     "copy-webpack-plugin": "~4.0.1",
     "extract-text-webpack-plugin": "~2.1.0",
     "lazy": "1.0.11",
     "nativescript-css-loader": "~0.26.0",
     "nativescript-dev-typescript": "~0.4.0",
     "nativescript-dev-webpack": "^0.6.3",
     "raw-loader": "~0.5.1",
     "resolve-url-loader": "~2.0.2",
     "typescript": "~2.2.1",
     "webpack": "~2.6.1",
     "webpack-sources": "~1.0.1"
   },
   "scripts": {
     "ns-bundle": "ns-bundle",
     "start-android-bundle": "npm run ns-bundle --android --run-app",
     "start-ios-bundle": "npm run ns-bundle --ios --run-app",
     "build-android-bundle": "npm run ns-bundle --android --build-app",
     "build-ios-bundle": "npm run ns-bundle --ios --build-app",
     "publish-ios-bundle": "npm run ns-bundle --ios --publish-app"
   }
}

*webpack.config.js*

const { resolve, join  } = require("path");

const webpack = require("webpack");
const nsWebpack = require("nativescript-dev-webpack");
const nativescriptTarget = 
require("nativescript-dev-webpack/nativescript-target");
const CopyWebpackPlugin = require("copy-webpack-plugin");
const ExtractTextPlugin = require("extract-text-webpack-plugin");

const { AotPlugin } = require("@ngtools/webpack");

const mainSheet = `app.css`;

module.exports = env => {
     const platform = getPlatform(env);

     // Default destination inside platforms/<platform>/...
     const path = resolve(nsWebpack.getAppPath(platform));

     const entry = {
         // Discover entry module from package.json
         bundle: `./${nsWebpack.getEntryModule()}`,

         // Vendor entry with third-party libraries
         vendor: `./vendor`,

         // Entry for stylesheet with global application styles
         [mainSheet]: `./${mainSheet}`,
     };

     const rules = getRules();
     const plugins = getPlugins(platform, env);
     const extensions = getExtensions(platform);

     return {
         context: resolve("./app"),
         target: nativescriptTarget,
         entry,
         output: {
             pathinfo: true,
             path,
             libraryTarget: "commonjs2",
             filename: "[name].js",
         },
         resolve: {
             extensions,

             // Resolve {N} system modules from tns-core-modules
             modules: [
                 "node_modules/tns-core-modules",
                 "node_modules",
             ]
         },
         node: {
             // Disable node shims that conflict with NativeScript
             "http": false,
             "timers": false,
             "setImmediate": false,
             "fs": "empty",
         },
         module: { rules },
         plugins,
     };
};


function getPlatform(env) {
     return env.android ? "android" :
         env.ios ? "ios" :
         () => { throw new Error("You need to provide a target 
platform!") };
}

function getRules() {
     return [
         {
             test: /\.html$|\.xml$/,
             use: [
                 "raw-loader",
             ]
         },
         // Root stylesheet gets extracted with bundled dependencies
         {
             test: new RegExp(mainSheet),
             use: ExtractTextPlugin.extract([
                 {
                     loader: "resolve-url-loader",
                     options: { silent: true },
                 },
                 {
                     loader: "nativescript-css-loader",
                     options: { minimize: false }
                 },
                 "nativescript-dev-webpack/platform-css-loader",
             ]),
         },
         // Other CSS files get bundled using the raw loader
         {
             test: /\.css$/,
             exclude: new RegExp(mainSheet),
             use: [
                 "raw-loader",
             ]
         },
         // SASS support
         {
             test: /\.scss$/,
             use: [
                 "raw-loader",
                 "resolve-url-loader",
                 "sass-loader",
             ]
         },


         // Compile TypeScript files with ahead-of-time compiler.
         {
             test: /\.ts$/,
             loaders: [
                 "nativescript-dev-webpack/tns-aot-loader",
                 "@ngtools/webpack",
             ]
         }

     ];
}

function getPlugins(platform, env) {
     let plugins = [
         new ExtractTextPlugin(mainSheet),

         // Vendor libs go to the vendor.js chunk
         new webpack.optimize.CommonsChunkPlugin({
             name: ["vendor"],
         }),

         // Define useful constants like TNS_WEBPACK
         new webpack.DefinePlugin({
             "global.TNS_WEBPACK": "true",
         }),

         // Copy assets to out dir. Add your own globs as needed.
         new CopyWebpackPlugin([
             { from: mainSheet },
             { from: "css/**" },
             { from: "fonts/**" },
             { from: "**/*.jpg" },
             { from: "**/*.png" },
             { from: "**/*.xml" },
         ], { ignore: ["App_Resources/**"] }),

         // Generate a bundle starter script and activate it in package.json
         new nsWebpack.GenerateBundleStarterPlugin([
             "./vendor",
             "./bundle",
         ]),

         // Angular AOT compiler
         new AotPlugin({
             tsConfigPath: "tsconfig.aot.json",
             entryModule: resolve(__dirname, "app/app.module#AppModule"),
             typeChecking: false
         }),

         // Resolve .ios.css and .android.css component stylesheets, and 
.ios.html and .android component views
         new nsWebpack.UrlResolvePlugin({
             platform: platform,
             resolveStylesUrls: true,
             resolveTemplateUrl: true
         }),

     ];

     if (env.uglify) {
         plugins.push(new webpack.LoaderOptionsPlugin({ minimize: true }));

         // Work around an Android issue by setting compress = false
         const compress = platform !== "android";
         plugins.push(new webpack.optimize.UglifyJsPlugin({
             mangle: { except: nsWebpack.uglifyMangleExcludes },
             compress,
         }));
     }

     return plugins;
}

// Resolve platform-specific modules like module.android.js
function getExtensions(platform) {
     return Object.freeze([
         `.${platform}.ts`,
         `.${platform}.js`,
         ".aot.ts",
         ".ts",
         ".js",
         ".css",
         `.${platform}.css`,
     ]);
}

Regards,
*Nathakorn J.*
Softoo Systems Co., Ltd.
www.softoo.co.th

**Comment by tsonevn** [comment]
Hi @NathakornJ,
I am attaching the requested files, you could review it and verify, whether there are some changes.



[Archive.zip](https://github.com/NativeScript/nativescript-dev-webpack/files/1097181/Archive.zip)

**Comment by NathakornJ** [comment]
Hi Tsonev,

Thanks. After a lot of tries and fixed over last weekend, fortunately, I 
successfully made webpack working for my project (though, I still don't 
know the root cause). The result starts up 50% faster, from >20s to 
about 10s. With a release build, it achieves about 8s. This is promising.

Regards,
*Nathakorn J.*

**Comment by lukashlobil** [comment]
I am not sure whether to create a new issue or just post it here. I used AOT with 2.5.0 and it worked fine. Now I bumped it to version 3.0.1 and it runs without AOT, but ns-bundle fails. The bad thing is, it doesn't give me any information. It shows some Typescript errors (it didn't before), but then says bundling of the file went ok. My package.json and tsconfig are [here](https://gist.github.com/lukashlobil/c0453096364bcc1f644fa89bdfa7b7e0) - can you have a look? Maybe you'll spot something.

This is the last line of the AOT build:

> Child extract-text-webpack-plugin:
>        [0] ../~/nativescript-css-loader/lib/css-base.js 1.51 kB {0} [built]
>        [1] ../~/nativescript-css-loader?{"minimize":false}!./css/custom.css 3.04 kB {0} [built]
>        [2] ../~/nativescript-css-loader?{"minimize":false}!../~/nativescript-theme-core/css/core.light.android.css 13.9 kB {0} [built]
>        [3] ../~/resolve-url-loader?{"silent":true,"absolute":false,"sourceMap":false,"fail":false,"keepQuery":false,"debug":false,"root":null}!../~/nativescript-css-loader?{"minimize":false}!../~/nativescript-dev-webpack/platform-css-loader.js!./app.css 3.35 kB {0} [built]
> child process exited with code 2
>

**Comment by behi1ty** [comment]
1. tns create test --ng 
2. cd test
3. npm install --save-dev nativescript-dev-webpack 
4. npm install 
    npm WARN @ngtools/webpack@1.4.2 requires a peer of webpack@^2.2.0 but none was installed.
    npm WARN extract-text-webpack-plugin@2.1.2 requires a peer of webpack@^2.2.0 but none was   installed.
     npm WARN nativescript-imagepicker@3.0.2 requires a peer of nativescript-telerik-ui@^3.0.0 but none was installed.
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2:                    wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch"
:"x64"})

5. npm run build-android-bundle
reulst : 
Running tns prepare...
module.js:472
    throw err;


tns --version : 3.1.2
ng --version : 1.2.0
tsc --version : 2.4.1
node --version : 7.9.0
npm --version : 5.1.0

how problem?
